// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
scsmodbus_path=get_absolute_file_path('loader.sce');
link(scsmodbus_path+'libscsmodbus.so',['mb_init_tcp','mb_init_rtu','mb_read','mb_write','mb_write2'],'c');
